[package]
name = "server-framework"
version = "0.1.0"
edition = "2021"
authors = ["Embark <opensource@embark-studios.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/server-framework"
homepage = "https://github.com/EmbarkStudios/server-framework"
repository = "https://github.com/EmbarkStudios/server-framework"
description = "Opinionated framework for running network servers"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework", "service"]

[dependencies]
axum = { version = "0.3", features = ["http2"] }
clap = "3.0.0-beta.5"

[dependencies.tower]
version = "0.4"
features = [
    # ...
]

[dependencies.tower-http]
version = "0.1"
features = [
    # ...
]

[dev-dependencies]

[workspace]
members = ["examples/*"]

# TODO: before publishing this crate, publish new version of axum and tower-http
# and remove these patches
[patch.crates-io]
axum = { git = "https://github.com/tokio-rs/axum.git" }
tower-http = { git = "https://github.com/tower-rs/tower-http.git" }
