[package]
name = "example-axum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
server-framework = { path = "../../" }
tokio = { version = "1.14", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
